---
- name: Install with APT | Install dependencies
  ansible.builtin.apt:
    name:
      - gnupg
      - software-properties-common
    update_cache: true
    state: present
  become: true

- name: Install with APT | Add HashiCorp GPG key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /etc/apt/trusted.gpg.d/hashicorp-archive-keyring.asc
    mode: "0644"
  become: true

- name: Install with APT | Add official HashiCorp repository
  ansible.builtin.apt_repository:
    repo: deb https://apt.releases.hashicorp.com {{ ansible_facts['distribution_release'] }} main
    filename: hashicorp
    state: present
    update_cache: true
  become: true

- name: Install with APT | Install Terraform
  ansible.builtin.apt:
    name: terraform
    update_cache: true
    state: present
  become: true
